name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # test:
  #   uses: ./.github/workflows/test.yml
  #   secrets: inherit

  build:
    runs-on: ubuntu-latest
    # needs: test
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - name: Setup NPM token
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
      - name: Install
        run: yarn install --frozen-lockfile --non-interactive
      - name: Drop changes to .npmrc file
        run: git checkout -- .npmrc
      - name: Generate client
        run: yarn generate
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Update API Client
          commit-message: "feat: update api client"
          team-reviewers: aurora-is-near/apps
          token: ${{ secrets.GH_SEMANTIC_RELEASE_TOKEN }}
      - name: Enable auto-merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GH_SEMANTIC_RELEASE_TOKEN }}
      - name: Approve the PR
        run: |
          gh pr checkout "$PR_URL"
            if [ "$(gh pr status --json reviewDecision -q .currentBranch.reviewDecision)" != "APPROVED" ];
          then
            gh pr review --approve "$PR_URL"
          else
            echo "PR already approved.";
          fi
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GH_SEMANTIC_RELEASE_TOKEN }}
